packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - "esbuild"
  - "prisma"
  - "sharp"

allowBuilds:
  "@parcel/watcher": true
  "@prisma/client": true
  "@prisma/engines": true
  "@swc/core": true
  "esbuild": true
  "prisma": true
  "sharp": true
