export const INITIAL_VEHICLES = [
  {
    code: 'sedan',
    name: 'Sedan',
    subtitle: 'Sedan / SUV',
    maxPax: 3,
    maxLuggage: 3,
    image: 'https://pub-f6310552a1b646efb46a653a7f05720c.r2.dev/assets/flota/suv-privado-andes.webp',
    features: ['Chofer profesional', 'A/C en todo el trayecto', 'Privado — sin compartir'],
    order: 1,
  },
  {
    code: 'minivan',
    name: 'MiniVan',
    subtitle: 'Minivan Ejecutiva',
    maxPax: 6,
    maxLuggage: 6,
    image: 'https://pub-f6310552a1b646efb46a653a7f05720c.r2.dev/assets/flota/minivan-valle-sagrado.webp',
    features: ['Chofer profesional', 'A/C en todo el trayecto', 'Privado — sin compartir'],
    order: 2,
  },
  {
    code: 'benz-10',
    name: 'Mercedes Benz 10pax',
    subtitle: 'Minibús Turístico 10',
    maxPax: 10,
    maxLuggage: 10,
    image: 'https://pub-f6310552a1b646efb46a653a7f05720c.r2.dev/assets/flota/sprinter-cusco.webp',
    features: ['Chofer profesional', 'A/C en todo el trayecto', 'Privado — sin compartir'],
    order: 3,
  },
  {
    code: 'benz-15',
    name: 'Mercedes Benz 15pax',
    subtitle: 'Sprinter Turística 15',
    maxPax: 15,
    maxLuggage: 10,
    image: 'https://pub-f6310552a1b646efb46a653a7f05720c.r2.dev/assets/flota/sprinter-cusco.webp',
    features: ['Chofer profesional', 'A/C en todo el trayecto', 'Privado — sin compartir'],
    order: 4,
  },
];

export const INITIAL_TRANSFERS = [
  {
    title: 'Aeropuerto Alejandro Velasco Astete a Hotel Cusco Centro',
    slug: 'aeropuerto-cusco-hotel-cusco',
    origin: 'Aeropuerto Alejandro Velasco Astete (CUZ)',
    destination: 'Hotel en Cusco Centro Histórico',
    duration: '20-30 min',
    tripType: 'Solo ida',
    hasSharedService: true,
    sharedPrice: 8,
    hasPrivateService: true,
    order: 1,
    vehiclePrices: {
      sedan: 20,
      minivan: 25,
      'benz-10': 30,
      'benz-15': 35,
    },
  },
  {
    title: 'Hotel Cusco Centro a Aeropuerto Alejandro Velasco Astete',
    slug: 'hotel-cusco-aeropuerto-cusco',
    origin: 'Hotel en Cusco Centro Histórico',
    destination: 'Aeropuerto Alejandro Velasco Astete (CUZ)',
    duration: '20-30 min',
    tripType: 'Solo ida',
    hasSharedService: true,
    sharedPrice: 8,
    hasPrivateService: true,
    order: 2,
    vehiclePrices: {
      sedan: 20,
      minivan: 25,
      'benz-10': 30,
      'benz-15': 35,
    },
  },
  {
    title: 'Cusco a Estación de Tren Ollantaytambo (Machu Picchu)',
    slug: 'cusco-estacion-ollantaytambo',
    origin: 'Cusco (Hotel / Centro)',
    destination: 'Estación de Tren Ollantaytambo',
    duration: '1 hr 45 min',
    tripType: 'Solo ida',
    hasSharedService: true,
    sharedPrice: 15,
    hasPrivateService: true,
    order: 3,
    vehiclePrices: {
      sedan: 45,
      minivan: 65,
      'benz-10': 90,
      'benz-15': 120,
    },
  },
  {
    title: 'Estación de Tren Ollantaytambo a Hotel en Cusco',
    slug: 'estacion-ollantaytambo-cusco',
    origin: 'Estación de Tren Ollantaytambo',
    destination: 'Cusco (Hotel / Centro)',
    duration: '1 hr 45 min',
    tripType: 'Solo ida',
    hasSharedService: true,
    sharedPrice: 15,
    hasPrivateService: true,
    order: 4,
    vehiclePrices: {
      sedan: 45,
      minivan: 65,
      'benz-10': 90,
      'benz-15': 120,
    },
  },
  {
    title: 'Cusco a Estación de Tren Poroy',
    slug: 'cusco-estacion-poroy',
    origin: 'Cusco (Hotel / Centro)',
    destination: 'Estación de Tren Poroy',
    duration: '35 min',
    tripType: 'Solo ida',
    hasSharedService: true,
    sharedPrice: 10,
    hasPrivateService: true,
    order: 5,
    vehiclePrices: {
      sedan: 25,
      minivan: 35,
      'benz-10': 45,
      'benz-15': 60,
    },
  },
  {
    title: 'Cusco a Hoteles en Urubamba (Valle Sagrado)',
    slug: 'cusco-hoteles-urubamba',
    origin: 'Cusco (Hotel / Aeropuerto)',
    destination: 'Hoteles en Urubamba',
    duration: '1 hr 15 min',
    tripType: 'Solo ida',
    hasSharedService: true,
    sharedPrice: 15,
    hasPrivateService: true,
    order: 6,
    vehiclePrices: {
      sedan: 40,
      minivan: 55,
      'benz-10': 80,
      'benz-15': 110,
    },
  },
  {
    title: 'Cusco a Pueblo de Pisac',
    slug: 'cusco-pueblo-pisac',
    origin: 'Cusco (Hotel / Centro)',
    destination: 'Pisac (Pueblo / Mercado)',
    duration: '50 min',
    tripType: 'Solo ida',
    hasSharedService: true,
    sharedPrice: 12,
    hasPrivateService: true,
    order: 7,
    vehiclePrices: {
      sedan: 30,
      minivan: 45,
      'benz-10': 60,
      'benz-15': 85,
    },
  },
  {
    title: 'Cusco a Pueblo Textil de Chinchero',
    slug: 'cusco-pueblo-chinchero',
    origin: 'Cusco (Hotel / Centro)',
    destination: 'Chinchero (Talleres Textiles)',
    duration: '45 min',
    tripType: 'Solo ida',
    hasSharedService: true,
    sharedPrice: 12,
    hasPrivateService: true,
    order: 8,
    vehiclePrices: {
      sedan: 30,
      minivan: 45,
      'benz-10': 60,
      'benz-15': 85,
    },
  },
  {
    title: 'Cusco a Soraypampa (Base Laguna Humantay / Salkantay)',
    slug: 'hotel-cusco-soraypampa',
    origin: 'Cusco (Hotel / Centro)',
    destination: 'Soraypampa (Mollepata)',
    duration: '3 hrs',
    tripType: 'Solo ida',
    hasSharedService: true,
    sharedPrice: 25,
    hasPrivateService: true,
    order: 9,
    vehiclePrices: {
      sedan: 80,
      minivan: 110,
      'benz-10': 140,
      'benz-15': 180,
    },
  },
  {
    title: 'Cusco a Phulawasipata (Base Montaña 7 Colores)',
    slug: 'hotel-cusco-phulawasipata',
    origin: 'Cusco (Hotel / Centro)',
    destination: 'Phulawasipata (Cusipata)',
    duration: '3 hrs 30 min',
    tripType: 'Solo ida',
    hasSharedService: true,
    sharedPrice: 25,
    hasPrivateService: true,
    order: 10,
    vehiclePrices: {
      sedan: 90,
      minivan: 120,
      'benz-10': 150,
      'benz-15': 200,
    },
  },
];
