export const INITIAL_VEHICLES = [
  {
    code: 'sedan',
    name: 'Sedan',
    subtitle: 'Sedan / SUV',
    maxPax: 3,
    maxLuggage: 3,
    image: 'https://pub-f6310552a1b646efb46a653a7f05720c.r2.dev/assets/flota/suv-privado-andes.webp',
    features: ['Chofer profesional', 'A/C en todo el trayecto', 'Privado — sin compartir'],
    order: 1,
  },
  {
    code: 'minivan',
    name: 'MiniVan',
    subtitle: 'Minivan Ejecutiva',
    maxPax: 6,
    maxLuggage: 6,
    image: 'https://pub-f6310552a1b646efb46a653a7f05720c.r2.dev/assets/flota/minivan-valle-sagrado.webp',
    features: ['Chofer profesional', 'A/C en todo el trayecto', 'Privado — sin compartir'],
    order: 2,
  },
  {
    code: 'benz-10',
    name: 'Mercedes Benz 10pax',
    subtitle: 'Minibús Turístico 10',
    maxPax: 10,
    maxLuggage: 10,
    image: 'https://pub-f6310552a1b646efb46a653a7f05720c.r2.dev/assets/flota/sprinter-cusco.webp',
    features: ['Chofer profesional', 'A/C en todo el trayecto', 'Privado — sin compartir'],
    order: 3,
  },
  {
    code: 'benz-15',
    name: 'Mercedes Benz 15pax',
    subtitle: 'Sprinter Turística 15',
    maxPax: 15,
    maxLuggage: 10,
    image: 'https://pub-f6310552a1b646efb46a653a7f05720c.r2.dev/assets/flota/sprinter-cusco.webp',
    features: ['Chofer profesional', 'A/C en todo el trayecto', 'Privado — sin compartir'],
    order: 4,
  },
];

export const INITIAL_TRANSFERS = [
  {
    title: 'Aeropuerto de Cusco a Hotel Cusco',
    slug: 'aeropuerto-cusco-hotel-cusco',
    origin: 'Aeropuerto de Cusco',
    destination: 'Hotel Cusco',
    duration: '20-30 min',
    tripType: 'Solo ida',
    hasSharedService: true,
    sharedPrice: 8,
    hasPrivateService: true,
    order: 1,
    vehiclePrices: {
      sedan: 20,
      minivan: 25,
      'benz-10': 30,
      'benz-15': 35,
    },
  },
  {
    title: 'Hotel Cusco a Aeropuerto de Cusco',
    slug: 'hotel-cusco-aeropuerto-cusco',
    origin: 'Hotel Cusco',
    destination: 'Aeropuerto de Cusco',
    duration: '20-30 min',
    tripType: 'Solo ida',
    hasSharedService: true,
    sharedPrice: 8,
    hasPrivateService: true,
    order: 2,
    vehiclePrices: {
      sedan: 20,
      minivan: 25,
      'benz-10': 30,
      'benz-15': 35,
    },
  },
  {
    title: 'Hotel Cusco a Soraypampa',
    slug: 'hotel-cusco-soraypampa',
    origin: 'Hotel Cusco',
    destination: 'Soraypampa',
    duration: '3 hrs',
    tripType: 'Solo ida',
    hasSharedService: true,
    sharedPrice: 25,
    hasPrivateService: true,
    order: 3,
    vehiclePrices: {
      sedan: 80,
      minivan: 110,
      'benz-10': 140,
      'benz-15': 180,
    },
  },
  {
    title: 'Soraypampa a Hotel Cusco',
    slug: 'soraypampa-hotel-cusco',
    origin: 'Soraypampa',
    destination: 'Hotel Cusco',
    duration: '3 hrs',
    tripType: 'Solo ida',
    hasSharedService: true,
    sharedPrice: 25,
    hasPrivateService: true,
    order: 4,
    vehiclePrices: {
      sedan: 80,
      minivan: 110,
      'benz-10': 140,
      'benz-15': 180,
    },
  },
];
